### ISSUE TITLE
Homeassistant

### ISSUE THREAD

**Issue by tfael** [pablozg/freeds#21]
Hola, algún plan de desarrollar una integración en Homeassistant?

**Comment by pablozg** [comment]
Hola, en estos momentos estoy liado con temas de trabajo y estoy ultimando la última versión que voy a publicar antes de centrarme en el trabajo y serán unos dos o tres meses en los que sólo tocaré el proyecto para temas urgentes.

Respecto a HA no creo que vaya a desarrollar ninguna implementación a no ser que alguien lo haga por su cuenta, ya que uso Domoticz en su lugar y como te digo ahora mismo no tengo demasiado tiempo libre, pero te animo a que lo intentes tú directamente.

Un saludo.

**Comment by jorgestima** [comment]
I'm also using HA and indeed, it would be great to have some integration. For example, if just two things were possible to integrate in HA as ON/OFF button and target power value, that would be really good.

**Comment by fizcris** [comment]
Hi, 

I have started to do the integration here [aquí](https://github.com/fizcris/home-assistant-freeds).

But since then I have found [MQTT discovery](https://www.home-assistant.io/docs/mqtt/discovery/), whit this there is no need anymore for a has integration as if MQTT discovery is included in the ESP32 all the sensors would be automatically available in hassio as long as they are using the same broker.

**Comment by pablozg** [comment]
> I'm also using HA and indeed, it would be great to have some integration. For example, if just two things were possible to integrate in HA as ON/OFF button and target power value, that would be really good.

Hi, I suggest you to suscribe to the [Telegram Channel](https://t.me/freeds_es) and ask for the HA integration, I think someone it has done.

You can use a 'POST' message to freeDS to switch ON/OFF with http://FREEDSIP/tooglebuttons?data=6
And switch it between AUTO / MAN with http://FREEDSIP/tooglebuttons?data=7

Or use mqtt as fizcris said, in the future we can integrate MQTT discovery topics.

**Comment by jorgestima** [comment]
I know that MQTT is a possibility and very powerfull but more complicated to configure. As only recently I've entered in HA world, it is not easy for me to configure that. So, if a simple tool in HACS would be available, for me it would be great.

**Comment by fizcris** [comment]
> I know that MQTT is a possibility and very powerfull but more complicated to configure. As only recently I've entered in HA world, it is not easy for me to configure that. So, if a simple tool in HACS would be available, for me it would be great.
Hi,

I think even a native home assistant integration is developed (wich I don't see the need with MQTT discovery) it would be based on MQTT as it is the simplest way to relay infomation/control the freeds from hassio. 

I highly recommend you to install the[ Mosquitto Broker add-on](https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md) from the supervisor window.

Here below are some examples of how to add freeds sensors in the  .yaml configuration file that  I have used some time ago... You can use these examples to integrate the relevant parameter you need from freeds while a more suitable solution is developed.


```
  sensor:
  - platform: mqtt
    name: solar_power
    state_topic: "freeds_d7dc/wsolar"
    unit_of_measurement: "W"
    device_class: power
  
  - platform: mqtt
    name: grid_power
    state_topic: "freeds_d7dc/wgrid"
    unit_of_measurement: "W"
    device_class: power
  
  - platform: filter
    name: "Filtered grid power"
    entity_id: sensor.grid_power
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 4
        precision: 2
  
  - platform: filter
    name: "Net Power last 60s"
    entity_id: sensor.grid_power
    filters:
      - filter: time_simple_moving_average
        window_size: "00:00:60"
        precision: 2
  
  - platform: mqtt
    name: load_power
    state_topic: "freeds_d7dc/loadWatts"
    unit_of_measurement: "W"
    device_class: power
  
  - platform: integration
    source: sensor.solar_power
    name: solar_energy
    method: left
    unit_prefix: k
    round: 2
  
  - platform: integration
    source: sensor.grid_power_abs
    name: grid_energy
    method: left
    unit_prefix: k
    round: 2
  
  # - platform: integration
  #   source: sensor.grid_power
  #   name: net_grid_energy
  #   method: left
  #   unit_prefix: k
  #   round: 2
  
  - platform: integration
    source: sensor.load_power
    name: load_energy
    method: left
    unit_prefix: k
    round: 2
```
